language: android
android:
  components:
    - build-tools-23.0.1
    - tools
    - platform-tools
    - android-23
    - sysimg-23
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-[0-9a-f]{8}
    - '.*intel.+'
script: ./gradlew assemble
